### ISSUE TITLE
Crash with Psychonauts

### ISSUE THREAD

**Issue by cybercat5555** [cybercat5555/Miskatonic-Mysteries-Fabric#1]
Process: Had a Psychonaut around who was messing with a chemistry set. The bubble sound played then the game crashed. Was able to re-enter the world without an issue 
[crash-2021-01-06_00.41.34-server.txt](https://github.com/cybercat5555/Miskatonic-Mysteries-Fabric/files/5777733/crash-2021-01-06_00.41.34-server.txt)

**Comment by Aelpecyem** [comment]
cannot replicate
