### ISSUE TITLE
MM crashes modpack.

### ISSUE THREAD

**Issue by toErIpNid** [cybercat5555/Miskatonic-Mysteries-Fabric#12]
[crash-2021-05-04_01.11.12-client.txt](https://github.com/cybercat5555/Miskatonic-Mysteries-Fabric/files/6419252/crash-2021-05-04_01.11.12-client.txt)
1.16.5 minecraft, latest version of everything else.

**Comment by BrekiTomasson** [comment]
You don't seem to have the GeckoLib library installed.

**Comment by Aelpecyem** [comment]
install geckolib, it is a required dependency
