### ISSUE TITLE
Difficult-to-reproduce crash

### ISSUE THREAD

**Issue by BrekiTomasson** [cybercat5555/Miskatonic-Mysteries-Fabric#13]
Iä! Iä! Cthulhu fhtagn!

Been having a number of weird crashes that I haven't been able to narrow down to any given mod these past few weeks, the game crashes with a Biome Decoration error. It happens when the game generates villages - but not every time. See example crashlog here: https://gist.githubusercontent.com/natanfudge/4683ae4f28f46a7fa22649c9e05f9b1e/raw/9d053c743082fdfad0f61c5dbfed5c13a9384c41/crash.txt

When going through the ordinary process of disabling one mod at a time if it was a mod that did anything related to village generation, the game *seems* to have stopped crashing once I disabled Miskatonic Mysteries. I say "seems" because it's not always easy to reproduce, but efter visiting 20+ villages I'm feeling fairly confident.

I wish I could be of any more help, but take a look at the crash log I've enclosed; it might offer some hints as to what's going on here or suggest a mod incompatibility we've both overlooked.

**Comment by BrekiTomasson** [comment]
Okay, I've now had a Biome Decoration crash even with Miskatonic Mysteries disabled, so it turns out this mod might not have been responsible after all. Which is good, because it means I can add it back in! ... but bad, because it means the hunt continues.

**Comment by Aelpecyem** [comment]
I'll close the issue then
