### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by itsNordLord** [cybercat5555/Miskatonic-Mysteries-Fabric#14]
`miskatonic mysteries` version `0.0.3`

Log: https://paste.gg/p/anonymous/19a742d9c4334bb9bc078cf6836a269f
Line that is being spammed: `[15:13:05] [main/WARN]: You're trying to deserialize an object of type class [Lnet.minecraft.class_1799; from one of type class net.minecraft.class_1799. This is likely not what you want!` about 350~ times

It doesn't seem to be having any side effects and doesn't coincide with any crashes but it does fill up the console quite a bit. Only bug that I seem to have in my large modpack is that I cannot trade with some of the mod-added Villagers.

**Comment by Aelpecyem** [comment]
This is a Patchouli related bug, compare https://github.com/Vazkii/Patchouli/issues/390
