### ISSUE TITLE
Group Healing spell does nothing

### ISSUE THREAD

**Issue by Dual-Iron** [cybercat5555/Miskatonic-Mysteries-Fabric#17]
Whether cast through Group, Healing simply does nothing to mobs nor players.

https://cdn.discordapp.com/attachments/592116208715956324/842640519623868436/Minecraft__1.16.5_-_Multiplayer_3rd-party_Server_2021-05-14_01-51-29.mp4

**Comment by Aelpecyem** [comment]
I cannot reproduce the behavior with Self. If your player is already affiliated to Hastur, the Group medium will probably not affect your team mate

**Comment by Dual-Iron** [comment]
Ok, yeah, apparently the Healing spell simply doesn't work when possessing a mob using Requiem. I'll add that to #16. As for Group healing, what is its intended behavior? I assumed it would target all entities that have health and benefit from Instant Healing.

**Comment by Aelpecyem** [comment]
Currently Group is based on Affiliation. That is a not-so explicit mechanic based on what GOOs you play with. You can sort of find it out using inkblots (a yellow sign will appear when you're affiliated to Hastur). Since you're probably affiliated with Hastur, your non-affiliated friend might simply not benefit from this

**Comment by Aelpecyem** [comment]
Though tbh I feel like this could be changed, so that the group spell medium does become way more general, rather than specifying based on affiliation

**Comment by Dual-Iron** [comment]
> Currently Group is based on Affiliation. That is a not-so explicit mechanic based on what GOOs you play with. You can sort of find it out using inkblots (a yellow sign will appear when you're affiliated to Hastur). Since you're probably affiliated with Hastur, your non-affiliated friend might simply not benefit from this

Alright. I'll test when a fellow Hastur follower is online on my server and close the ticket if that resolves the issue.

> Though tbh I feel like this could be changed, so that the group spell medium does become way more general, rather than specifying based on affiliation

Yeah... otherwise everything becomes a lot less useful/intuitive. Being unable to cast spells like Knockback, Ignite, or Resistance on every entity nearby was confusing, and I never would've figured out how it worked.
