### ISSUE TITLE
Holding the key for opening/closing the spell GUI when you only have one spell prepared makes the GUI flicker uncontrollably

### ISSUE THREAD

**Issue by Dual-Iron** [cybercat5555/Miskatonic-Mysteries-Fabric#20]
When you have two or more spells prepared, holding the GUI key opens the GUI so you can move your mouse to select your spell of choice to ready. This functions normally. 

When you have only one spell prepared, holding the GUI key makes the GUI selection flicker uncontrollably. When you let go of the key, the spell may or may not be readied for casting—the result is unpredictable. **What is expected** is that holding the GUI key when you have a single spell prepared simply readies that spell, and that pressing the key while readied unreadies the spell.

https://cdn.discordapp.com/attachments/592116208715956324/842649734912278588/Minecraft__1.16.5_-_Multiplayer_LAN_2021-05-14_02-28-36.mp4

**Comment by Aelpecyem** [comment]
This is basically fixed with the overhaul
