### ISSUE TITLE
After relogging or dying, players cannot cast spells until interacting with an altar that has a Necronomicon

### ISSUE THREAD

**Issue by Dual-Iron** [cybercat5555/Miskatonic-Mysteries-Fabric#21]
After relogging or dying, the spellcasting GUI can't reappear, so you can't select or deselect spells. If you died and had a spell selected, that spell stays selected. This effect ends when you interact with an altar that has a Necronomicon.

https://streamable.com/x51ir4 <-- Video demonstration

**Comment by Aelpecyem** [comment]
I'm still not able to reproduce this, even outside of dev environment. Can you make sure this happens with only MM and depedencies installed?

**Comment by Dual-Iron** [comment]
The dying part happens with no other mods installed. The relogging part appears to be another mod's doing.

**Comment by Aelpecyem** [comment]
I'll reopen this for until the other part with relogging is fixed

**Comment by Dual-Iron** [comment]
The file `fabrictailor_fabric-1.5.0-1.16.5.jar` is the culprit in my modpack. [Here](https://www.curseforge.com/minecraft/mc-mods/fabrictailor) is their CurseForge page. Good luck!
