### ISSUE TITLE
Group medium does not check isDead() for target entities, while Self does

### ISSUE THREAD

**Issue by Dual-Iron** [cybercat5555/Miskatonic-Mysteries-Fabric#24]
This leads to odd behavior. For example, Self Healing does not heal undead, but Group Healing does. Using Requiem, this causes obvious weirdness.

Compare: 
https://github.com/cybercat5555/Miskatonic-Mysteries-Fabric/blob/dd54b0bd94f1c71aebc79e73311fac603faf548d/src/main/java/com/miskatonicmysteries/common/feature/spell/medium/SelfSpellMedium.java#L17 https://github.com/cybercat5555/Miskatonic-Mysteries-Fabric/blob/dd54b0bd94f1c71aebc79e73311fac603faf548d/src/main/java/com/miskatonicmysteries/common/feature/spell/medium/GroupSpellMedium.java#L25

**Comment by Aelpecyem** [comment]
i forgot to close this oops
