### ISSUE TITLE
Starting a world with just Miskatonic Mysteries, and libraries crashes

### ISSUE THREAD

**Issue by HyperlyBola** [cybercat5555/Miskatonic-Mysteries-Fabric#25]
I also have another issue where Miskatonic Mysteries or Patchouli crashes when trying to click on any spell or when going to the next page on the introduction page. But those crashes were happening when I was using a modpack which is why i've been trying to test the mod by itself.

Edit:
Weirdly enough it runs and starts without errors when I use my modpack but I still have the issue of the book crashing my game when going to certain pages.

[https://pastebin.com/vs41uYFj](url) Book crash (might be patchouli)
[https://pastebin.com/n0MNfkTw](url)

**Comment by Fourmisain** [comment]
I was running into the book crash too.
Miskatonic Mysteries 0.0.5 only works with Patchouli-1.16.4-50, so you might need to downgrade.

**Comment by Aelpecyem** [comment]
this should be fixed in later versions
