### ISSUE TITLE
Necronomicon Issue

### ISSUE THREAD

**Issue by Acetraineraidan6** [cybercat5555/Miskatonic-Mysteries-Fabric#27]
So Im trying to start the mod and I began to mess with it in creative to get a feel for the mod but I can't get to the 2nd page of the introduction, what happens is I press next then it says saving world and crashes me back to the launcher (For reference I use the curseforge launcher)

**Comment by cybercat5555** [comment]
This is caused by using too new a version of Patchouli with MM, which is currently built for the previous major version. Downgrade your Patchi, but this will be fixed in the next major release of MM.

**Comment by Acetraineraidan6** [comment]
Oh thanks for the help Ill try this out
