### ISSUE TITLE
Crash relating to Players and Yellow Sign (?)

### ISSUE THREAD

**Issue by cybercat5555** [cybercat5555/Miskatonic-Mysteries-Fabric#3]
Was holding a shield with a Yellow Sign, was also standing near some Yellow Serfs, game decided to crash. Unsure if that is related.
[crash-2021-01-07_16.45.10-server.txt](https://github.com/cybercat5555/Miskatonic-Mysteries-Fabric/files/5784135/crash-2021-01-07_16.45.10-server.txt)

**Comment by Aelpecyem** [comment]
Looking through mappings it's probably a packeting issue

**Comment by Aelpecyem** [comment]
since I do not know what causes this, I'll close it in the future in case i accidentally fixed it

**Comment by Aelpecyem** [comment]
cannot replicate
