### ISSUE TITLE
Clicking on some Items in JEI Crashes world

### ISSUE THREAD

**Issue by Fade-Alchemist** [cybercat5555/Miskatonic-Mysteries-Fabric#33]
Like the title says.  They seem to be related to the chemistry set.

**Comment by SPYROHAWK** [comment]
I was about to make a post about this. I've specifically found that looking at rotten flesh uses in REI in the "Illegal Chemistry" section causes a crash.

Here's my crash log for details:

[crash-2021-07-22_13.47.39-client.txt](https://github.com/cybercat5555/Miskatonic-Mysteries-Fabric/files/6864243/crash-2021-07-22_13.47.39-client.txt)

**Comment by Derpford** [comment]
The fact that it's an ArrayIndexOutOfBounds suggests that something in that recipe is causing something to look at an array in a weird way. Near as I can tell, the only recipe in the chemistry set that applies to rotten flesh is the Re-Agent recipe.

I don't know much about Fabric modding, but digging around in some of the stuff for the stacktrace revealed [*this* line](https://github.com/cybercat5555/Miskatonic-Mysteries-Fabric/blob/58d5e53bcf7dd60efad733ea95352c5cb8538d99/src/main/java/com/miskatonicmysteries/client/compat/rei/category/ChemistrySetCategory.java#L56). If I had to guess, this list isn't getting populated with all the expected items. ReAgent is also the only item I can see in the Chemistry Set recipe list that uses a *tag* in one of the item slots, which explains why it only seems to happen on the ReAgent recipe.

I'm not sure why it's not populating that list properly, but for now you could probably fix it by replacing the RedMeat tag with just rotten flesh for the moment.

**Comment by Derpford** [comment]
Having just tested it, that change does not fix it. Wish it'd tell me which recipe is causing the crash...

**Comment by Derpford** [comment]
Wait. I've got it.

Java is zero-indexed, but these arrays use 1 as the starting index.

**Comment by Derpford** [comment]
Adding a sixth item to the recipe solves the problem. I guess whatever's registering the recipes isn't handling cases where the input list isn't exactly six items long?

**Comment by Aelpecyem** [comment]
this has been fixed indev on 1.17, you'll have to wait a bit till it releases
