### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by RustVEVO** [cybercat5555/Miskatonic-Mysteries-Fabric#34]
Whenever I attempt to launch my game with just Miskatonic Mysteries and it's dependencies, my launcher gets a crash message before the game even gets to launch, I believe I have everything installed correctly, but I may be wrong.
My modlist is
Cardinal-Components-API-2.8.3
config-2-4.5.7
fabric-api-0.36.0+1.16
geckolib-fabric-1.16.5-3.0.42
miskatonicmysteries-0.0.7
Patchouli-1.16.4-53-FABRIC
trinkets-2.6.7

And my fabric version is fabric-loader-0.11.6-1-1.16.5

Anyone know what's up?

**Comment by Aelpecyem** [comment]
Can you give a full crash log please

**Comment by RustVEVO** [comment]
> Can you give a full crash log please
Here you are!
[latest.log](https://github.com/cybercat5555/Miskatonic-Mysteries-Fabric/files/6849271/latest.log)

**Comment by Aelpecyem** [comment]
there's no crash in this crash log, are you sure you got the right one?

**Comment by RustVEVO** [comment]
> there's no crash in this crash log, are you sure you got the right one?

Apologies, after reinstalling all the dependencies, I've managed to get something more
[crash-2021-07-20_11.46.37-client.txt](https://github.com/cybercat5555/Miskatonic-Mysteries-Fabric/files/6849642/crash-2021-07-20_11.46.37-client.txt)

**Comment by Aelpecyem** [comment]
You need to update patchouli to latest 1.16 version

**Comment by RustVEVO** [comment]
Thank you, it seems to be working now!
