### ISSUE TITLE
Will this be updated to newer versions

### ISSUE THREAD

**Issue by NixityNull** [cybercat5555/Miskatonic-Mysteries-Fabric#35]
Ideally 1.17 but any is fine, i just really like this mod (plus it's the only eldrich horror themed mod for current versions) and i hope this mod doesn't fade into obscurity

**Comment by cybercat5555** [comment]
If you look at the repo there is stuff for 1.17. Its just on hold rn since we're working on a Spookyjam mod and we're also trying to include some new content with the port
