### ISSUE TITLE
curious banner pattern not working

### ISSUE THREAD

**Issue by joeballs12** [cybercat5555/Miskatonic-Mysteries-Fabric#46]
i can use it in rituals but not in looms,is this a bug?if so please fix

**Comment by Aelpecyem** [comment]
can you replicate exactly what you mean and post details such as other mods you're using?

**Comment by joeballs12** [comment]
i try to use curious banner pattern in a loom but i cant place it in,im only using miskatonic mysteries and it's dependencies

**Comment by cybercat5555** [comment]
Are you including a dye with it? Its working fine for me
![2022-05-18_17 41 33](https://user-images.githubusercontent.com/17956808/169160725-fdd3be0b-b989-4808-9443-3cfaeeef3b33.png)
