### ISSUE TITLE
Certain entities vanish when too far away

### ISSUE THREAD

**Issue by cybercat5555** [cybercat5555/Miskatonic-Mysteries-Fabric#53]
(Repost of issue from discord)

Certain entities, when one gets too far from them, seem to vanish. May involve tracking range, as it seems the mob being geckolib'd or not doesn't seem to be a connecting factor.

Affected entities:

- Byakhee
- Cultists
- Tentacle

Unaffected entities:

- Protagonist
- Feaster

**Comment by Aelpecyem** [comment]
Fixed by increasing tracking distance
