### ISSUE TITLE
Some commands not working

### ISSUE THREAD

**Issue by SPYROHAWK** [cybercat5555/Miskatonic-Mysteries-Fabric#57]
I apologize for not having exact error messages and whatnot, I came across this issue yesterday.

Basically, some commands work, some don't. Off the top of my head:

Working:
* Setting Ascension progress
* Setting max spell pool
* Setting max spell power

Not Working:
* Giving player blessings
* Giving player new spell effects
* Giving player new spell mediums
* Giving / checking player sanity?

All of the not working ones gave the same red error message in chat, but I forget what that was exactly.

**Comment by Aelpecyem** [comment]
This has been fixed in a recent commit. A new build will be released within this week
