### ISSUE TITLE
Server Crash when performing the Final Ritual for Hastur

### ISSUE THREAD

**Issue by thedeerirty** [cybercat5555/Miskatonic-Mysteries-Fabric#59]
The Simu-thingy. I can't spell it, that's on me.
[crash-2022-07-26_16.34.02-server.txt](https://github.com/cybercat5555/Miskatonic-Mysteries-Fabric/files/9193209/crash-2022-07-26_16.34.02-server.txt)
 
Off the top of my head? Maaaybe it conflicting with a modded biome in whatever its doing? I'm not sure.

**Comment by Aelpecyem** [comment]
fixed in 0.1.2
