### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Blade82001** [cybercat5555/Miskatonic-Mysteries-Fabric#6]
Game crashes on startup on a fresh instance. Disabling MM causes game to load normally.

**Comment by Blade82001** [comment]
https://pastebin.com/m7jeu3gi

**Comment by Aelpecyem** [comment]
do you have cloth config installed

**Comment by Blade82001** [comment]
i don't think that was listed as one of the dependencies. i installed it and it works now thanks!
