### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by KamiSami** [cybercat5555/Miskatonic-Mysteries-Fabric#7]
Hi, i was about to try run server with this said mod, but it appears this crashes server on launch.

**Comment by KamiSami** [comment]
Also quick question as i was trying the mod in singleplayer... What do you do to make serf "loyal" to you exactly?

**Comment by Aelpecyem** [comment]
it'd help if you posted a crashlog

**Comment by Aelpecyem** [comment]
> 
> 
> Also quick question as i was trying the mod in singleplayer... What do you do to make serf "loyal" to you exactly?

and you need a blessing for that, but often it refers to villager reputation

**Comment by KamiSami** [comment]
Here, didn't post log earlier mainly due to expecting this was reproduceable, but since you asked, i'll give it.
https://pastebin.com/TYEegxTg
I don't personally see much but it does say something about this mod at one point which led me thinking this mod may cause it, which is "[19:58:11] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'miskatonicmysteries'!"

**Comment by Aelpecyem** [comment]
Ok I messed up, this will be fixed in the first full release
