### ISSUE TITLE
Game wont open when playing with gigeresque and associated apis 1.19.2 fabric 0.14.14

### ISSUE THREAD

**Issue by sevenx13** [cybercat5555/Miskatonic-Mysteries-Fabric#99]
game tries to open to title screen but all the words are squares and it quickly returns to red loading screen and continues to try and fail to load game, game wont crash or do literally anything so im unable to give a crash log, any help would be appreciated

**Comment by mrsterner** [comment]
There always a latest.log

**Comment by sevenx13** [comment]
[latest.log](https://github.com/cybercat5555/Miskatonic-Mysteries-Fabric/files/10785169/latest.log)
